
CC=gcc
CFLAGS=-Wall -Wextra -std=c99
SRC=main.c list.c linkedlist.c tree.c map.c stack.c queue.c doublylinkedlist.c set.c priorityqueue.c circularbuffer.c deque.c bitset.c heap.c trie.c graph.c

all:
	$(CC) $(CFLAGS) $(SRC) -o data-types

clean:
	rm -f data-types
